service: serverless-plugin-python

custom:
  lumigo:
    token: 1234
    enhance_print: true
    should_report: false

provider:
  name: aws
  runtime: python3.7
  environment:
    LUMIGO_DEBUG: "TRUE"

functions:
  hello:
    handler: handler.hello

plugins:
  - ./../../../serverless-lumigo-plugin
  - serverless-python-requirements
