service: serverless-plugin-python

custom:
  lumigo:
    token: 1234
    enhance_print: true
    should_report: false
    skipReqCheck: true

provider:
  name: aws
  runtime: python3.7
  environment:
    LUMIGO_DEBUG: "TRUE"

functions:
  test:
    handler: handler.hello

plugins:
  - ./../../src/index
  - serverless-python-requirements
